### ISSUE TITLE
Is it possible to use the downgrade feature From FileSystem instead of FromAssemby?

### ISSUE THREAD

**Issue by ChristianOnLine** [asimeonov/DbUp.Downgrade#14]
Hi @asimeonov,
I world like to know how to use the package with a configuration that read the scripts and downgrade scripts from File System.
Is it possible?

Thanks in advance

**Comment by asimeonov** [comment]
> Hi @asimeonov, I world like to know how to use the package with a configuration that read the scripts and downgrade scripts from File System. Is it possible?
> 
> Thanks in advance

Hi @ChristianOnLine, thanks for bringing this up. Yes the library if fully capable of working with FileSystem provider there are test showcasing how do work with all providers. The one that you are referring to is here https://github.com/asimeonov/DbUp.Downgrade/blob/6d18a88c5921ab6357a0364d0fdd83fb22267e8b/src/DbUp.Downgrade.SqlServer.Tests/DbUpDowngradeSqlServerTests.cs#L93

If you have any further questions I will be glad to help.
