### ISSUE TITLE
GO Statements In Downgrade Scripts Don't Work

### ISSUE THREAD

**Issue by chbjh** [asimeonov/DbUp.Downgrade#7]
Downgrade scripts don't work if they contain GO statements. Upgrade scripts containing GO's work, but not downgrades.

I am using DbUp,Downgrade 2.0.0

If needed, I can provide more detail.

**Comment by asimeonov** [comment]
Issue is addressed now the downgrade script provider respects the GO statements. If the issue persists please contact me.
